import type { BlogPost } from './blogApi';

const now = new Date().toISOString();

export const DEFAULT_ARTICLES: BlogPost[] = [
  {
    id: 'default-1',
    title: '10 Simple Ways to Strengthen Your Relationship Every Day',
    slug: 'strengthen-relationship-every-day',
    category: 'Relationship Tips',
    excerpt:
      'Small, consistent actions build the strongest bonds. Discover ten easy habits that help couples feel closer, more appreciated, and deeply connected over time.',
    content: '',
    image_url: '/images/blogs/relationship.webp',
    image_alt: 'Couple walking hand in hand on a cobblestone street',
    author: 'Loveons Team',
    published: true,
    published_at: now,
    reading_time: '4 min read',
    tags: ['love', 'daily habits', 'connection'],
    meta_title: '10 Simple Ways to Strengthen Your Relationship Every Day',
    meta_description:
      'Small, consistent actions build the strongest bonds. Discover ten easy habits that help couples feel closer and more connected.',
    created_at: now,
    updated_at: now,
  },
  {
    id: 'default-2',
    title: 'How to Communicate Better With Your Partner',
    slug: 'communicate-better-with-partner',
    category: 'Communication',
    excerpt:
      'Great communication is the foundation of every healthy relationship. Learn proven techniques that help couples listen deeply, express needs clearly, and truly understand each other.',
    content: '',
    image_url: '/images/blogs/communication.webp',
    image_alt: 'Couple engaged in a warm conversation at sunset',
    author: 'Loveons Team',
    published: true,
    published_at: now,
    reading_time: '5 min read',
    tags: ['communication', 'listening', 'trust'],
    meta_title: 'How to Communicate Better With Your Partner',
    meta_description:
      'Learn proven techniques that help couples listen deeply, express needs clearly, and truly understand each other.',
    created_at: now,
    updated_at: now,
  },
  {
    id: 'default-3',
    title: 'Fun Date Night Ideas You Can Do at Home',
    slug: 'fun-date-night-ideas-at-home',
    category: 'Date Ideas',
    excerpt:
      'You do not need to spend a lot to have a memorable evening together. From cooking a new recipe to stargazing on the balcony, these creative ideas will make any night feel special.',
    content: '',
    image_url: '/images/blogs/date-ideas.webp',
    image_alt: 'Couple enjoying a romantic dinner with candles',
    author: 'Loveons Team',
    published: true,
    published_at: now,
    reading_time: '3 min read',
    tags: ['date night', 'home activities', 'romance'],
    meta_title: 'Fun Date Night Ideas You Can Do at Home',
    meta_description:
      'Creative and affordable date night ideas to make any evening at home feel romantic and memorable.',
    created_at: now,
    updated_at: now,
  },
  {
    id: 'default-4',
    title: 'How to Resolve Arguments Without Hurting Each Other',
    slug: 'resolve-arguments-without-hurting',
    category: 'Conflict Resolution',
    excerpt:
      'Every couple disagrees sometimes — what matters is how you handle it. These practical strategies help you work through conflict with empathy, respect, and a focus on solutions.',
    content: '',
    image_url: '/images/blogs/conflict.webp',
    image_alt: 'Couple having a calm, open conversation indoors',
    author: 'Loveons Team',
    published: true,
    published_at: now,
    reading_time: '5 min read',
    tags: ['conflict', 'empathy', 'healthy arguments'],
    meta_title: 'How to Resolve Arguments Without Hurting Each Other',
    meta_description:
      'Practical strategies to help couples work through disagreements with empathy, respect, and a focus on solutions.',
    created_at: now,
    updated_at: now,
  },
  {
    id: 'default-5',
    title: 'The Importance of Quality Time in a Relationship',
    slug: 'importance-of-quality-time',
    category: 'Relationship Tips',
    excerpt:
      'Being physically present is not the same as being emotionally present. Find out why dedicated, distraction-free time together is one of the most powerful investments you can make in your relationship.',
    content: '',
    image_url: '/images/blogs/relationship-tips.webp',
    image_alt: 'Happy couple laughing and enjoying time together outdoors',
    author: 'Loveons Team',
    published: true,
    published_at: now,
    reading_time: '4 min read',
    tags: ['quality time', 'presence', 'bonding'],
    meta_title: 'The Importance of Quality Time in a Relationship',
    meta_description:
      'Why dedicated, distraction-free time together is one of the most powerful investments you can make in your relationship.',
    created_at: now,
    updated_at: now,
  },
  {
    id: 'default-6',
    title: 'Building Trust: The Cornerstone of a Lasting Relationship',
    slug: 'building-trust-lasting-relationship',
    category: 'Trust & Commitment',
    excerpt:
      'Trust is not built in a single moment — it grows through hundreds of small, consistent actions. Explore the key behaviours that strengthen trust and keep your relationship secure long-term.',
    content: '',
    image_url: '/images/blogs/trust.webp',
    image_alt: 'Couple forming a heart shape with their hands',
    author: 'Loveons Team',
    published: true,
    published_at: now,
    reading_time: '5 min read',
    tags: ['trust', 'commitment', 'security'],
    meta_title: 'Building Trust: The Cornerstone of a Lasting Relationship',
    meta_description:
      'Explore the key behaviours that strengthen trust and keep your relationship secure and fulfilling long-term.',
    created_at: now,
    updated_at: now,
  },
];
