import { AlertTriangle, Heart, XCircle, Info } from 'lucide-react';
import Seo from '../components/Seo';
import PageLayout from '../components/PageLayout';

const sections = [
  {
    icon: Info,
    title: 'Entertainment & Educational Purposes',
    paragraphs: [
      'All content provided by LoveIntimacyTips is for entertainment and educational purposes only. The compatibility calculator, recommendations, tips, and blog articles are designed to encourage healthy conversations between partners — not to replace professional guidance.',
    ],
  },
  {
    icon: XCircle,
    title: 'Not Relationship or Medical Advice',
    paragraphs: [
      'The recommendations generated by our calculator are not relationship advice, medical advice, or psychological counseling. Always consult a qualified relationship counselor, therapist, or medical professional for personal concerns.',
      'Every individual and relationship is unique. What works for one couple may not work for another. Use your own judgment and communicate openly with your partner.',
    ],
  },
  {
    icon: AlertTriangle,
    title: 'No Guarantee of Results',
    paragraphs: [
      'LoveIntimacyTips does not guarantee any specific results from following our recommendations. Compatibility scores are generated by a simple algorithm and should not be taken as a definitive measure of relationship health.',
      'Your relationship success depends on many factors beyond what any calculator can measure — including communication, trust, mutual effort, and professional support when needed.',
    ],
  },
  {
    icon: Heart,
    title: 'Consent & Safety',
    paragraphs: [
      'All intimacy should be based on mutual consent, comfort, and respect. Never pressure your partner into any activity they are not comfortable with. If you or your partner experience discomfort, stop immediately and consult a healthcare professional if needed.',
    ],
  },
];

export default function Disclaimer() {
  return (
    <>
      <Seo
        title="Disclaimer — LoveIntimacyTips"
        description="LoveIntimacyTips is for entertainment and educational purposes only. Read our full disclaimer regarding relationship and medical advice."
        path="/disclaimer"
      />
      <PageLayout
        title="Disclaimer"
        subtitle="Please read this carefully before using our tools."
      >
        <div className="space-y-6">
          {sections.map((s) => (
            <div key={s.title}>
              <div className="flex items-center gap-2 mb-2">
                <div className="flex-shrink-0 w-9 h-9 rounded-lg bg-amber-50 border border-amber-100 flex items-center justify-center">
                  <s.icon className="w-4 h-4 text-amber-500" />
                </div>
                <h2 className="font-display text-lg font-bold text-gray-800">{s.title}</h2>
              </div>
              <div className="space-y-2 pl-11">
                {s.paragraphs.map((p, i) => (
                  <p key={i} className="text-sm text-gray-600 leading-relaxed">{p}</p>
                ))}
              </div>
            </div>
          ))}

          <div className="flex items-start gap-3 p-4 rounded-xl bg-amber-50 border border-amber-100 mt-4">
            <AlertTriangle className="w-5 h-5 text-amber-500 flex-shrink-0 mt-0.5" />
            <p className="text-xs text-amber-700 leading-relaxed">
              By using LoveIntimacyTips, you acknowledge that you have read and understood this disclaimer. If you do not agree with any part of it, please discontinue use of the website.
            </p>
          </div>
        </div>
      </PageLayout>
    </>
  );
}
