import Seo from '../components/Seo';
import PageLayout from '../components/PageLayout';
import { BRAND } from '../lib/brand';

export default function Terms() {
  return (
    <>
      <Seo
        title="Terms & Conditions — Loveons"
        description="Read the Terms & Conditions for using Loveons real world dating guides, love calculator, cosmic tarot, and other website features."
        path="/terms"
      />

      <PageLayout
        title="Terms & Conditions"
        subtitle="A friendly overview of how things work when you hang out on Loveons."
      >
        <div className="space-y-8 text-sm leading-7 text-gray-600">

          <section>
            <h2 className="font-display text-lg font-bold text-gray-800 mb-2">
              1. Welcome to Loveons
            </h2>
            <p>
              By exploring {BRAND.name} or using our playful tools, you are agreeing to these simple rules. If any part of this layout does not sit well with you, we kindly ask that you take a break from the website.
            </p>
          </section>

          <section>
            <h2 className="font-display text-lg font-bold text-gray-800 mb-2">
              2. What We Do
            </h2>
            <p>
              {BRAND.name} is a space created to inspire real life romance, offline social interactions, and off app dating. We provide informational articles, fun calculators, and cosmic exploration tools designed to build joyful communication between people.
            </p>
          </section>

          <section>
            <h2 className="font-display text-lg font-bold text-gray-800 mb-2">
              3. Cosmic Tools & Calculators
            </h2>
            <p>
              Our Cosmic Love Calculator and Cosmic Love Tarot tools are built strictly for entertainment purposes. 
            </p>
            <p className="mt-3">
              The matching percentages, compatibility scores, and suggestions generated by these algorithms are non-scientific, non-medical, and do not represent actual relationship health or real life future predictions. They are purely meant to be lighthearted icebreakers.
            </p>
          </section>

          <section>
            <h2 className="font-display text-lg font-bold text-gray-800 mb-2">
              4. Offline Guides & Advice
            </h2>
            <p>
              The real world dating tips, location guides, and event ideas we publish are shared for general inspiration only. They are never a substitute for professional mental health guidance, couple counseling, or legal support. 
            </p>
            <p className="mt-3">
              You should always trust your own personal judgment and common sense when heading out to social events, clubs, or public spaces mentioned on our website.
            </p>
          </section>

          <section>
            <h2 className="font-display text-lg font-bold text-gray-800 mb-2">
              5. Sharing Information Safely
            </h2>
            <p>
              When you enter names or details into our fun tools, you are in full control of that data. For your own comfort and privacy, please avoid putting highly confidential, private, or unnecessary personal documents anywhere on the site.
            </p>
          </section>

          <section>
            <h2 className="font-display text-lg font-bold text-gray-800 mb-2">
              6. Respectful Use
            </h2>
            <p>
              We want Loveons to stay clean, welcoming, and warm. You agree to use this platform with good intentions. Please do not try to alter the web code, mess with our servers, or use our digital tools to cause trouble for other users.
            </p>
          </section>

          <section>
            <h2 className="font-display text-lg font-bold text-gray-800 mb-2">
              7. Content Ownership
            </h2>
            <p>
              The design layouts, text graphics, original branding symbols, and custom content on {BRAND.name} belong to our creative team. You are free to read and share them with friends for personal fun, but copying them for business use without asking us first is not allowed.
            </p>
          </section>

          <section>
            <h2 className="font-display text-lg font-bold text-gray-800 mb-2">
              8. Third-Party Elements
            </h2>
            <p>
              To keep our web server fast and steady, we occasionally rely on trustworthy external tech partners for hosting, website analytical tracking, and seamless email deliveries. These services maintain their own technical usage systems.
            </p>
          </section>

          <section>
            <h2 className="font-display text-lg font-bold text-gray-800 mb-2">
              9. Website Flow & Updates
            </h2>
            <p>
              While we work hard to keep {BRAND.name} up, responsive, and completely bug-free, we cannot assure that the website will always run non-stop or be totally free of quick server glitches.
            </p>
          </section>

          <section>
            <h2 className="font-display text-lg font-bold text-gray-800 mb-2">
              10. Friendly Boundaries
            </h2>
            <p>
              Our guides are provided on an as-is basis. {BRAND.name} and its builders will not be responsible for any real-world missteps, personal misunderstandings, or expectations built upon our cosmic algorithms or offline lifestyle articles.
            </p>
          </section>

          <section>
            <h2 className="font-display text-lg font-bold text-gray-800 mb-2">
              11. Tweaks to These Terms
            </h2>
            <p>
              As the off-app dating movement grows, we might tweak these terms to match our updates. When we drop any fresh text adjustments here, continuing to hang out on the site simply means you are down with the new path.
            </p>
          </section>

          <section>
            <h2 className="font-display text-lg font-bold text-gray-800 mb-2">
              12. Say Hello
            </h2>
            <p>
              If you have any honest questions or simply want to talk to the creative brains behind the project, drop us a line anytime at:
            </p>

            <a
              href={`mailto:${BRAND.email}`}
              className="inline-block mt-2 font-semibold text-loveons-500 hover:text-loveons-600"
            >
              {BRAND.email}
            </a>
          </section>

          <section className="pt-4 border-t border-gray-100">
            <p className="text-xs text-gray-400">
              Last updated: September 2026
            </p>
          </section>

        </div>
      </PageLayout>
    </>
  );
}
