
import Seo from '../components/Seo';
import PageLayout from '../components/PageLayout';
import { BRAND } from '../lib/brand';

export default function Terms() {
  return (
    <>
      <Seo
        title="Terms & Conditions — Loveons"
        description="Read the Terms & Conditions for using Loveons relationship tools, love calculator, tips, and other website features."
        path="/terms"
      />

      <PageLayout
        title="Terms & Conditions"
        subtitle="Please read these terms carefully before using Loveons."
      >
        <div className="space-y-8 text-sm leading-7 text-gray-600">

          <section>
            <h2 className="font-display text-lg font-bold text-gray-800 mb-2">
              1. Acceptance of Terms
            </h2>

            <p>
              By accessing or using {BRAND.name}, you agree to these Terms &
              Conditions. If you do not agree with any part of these terms,
              please do not use the website.
            </p>
          </section>

          <section>
            <h2 className="font-display text-lg font-bold text-gray-800 mb-2">
              2. About Loveons
            </h2>

            <p>
              {BRAND.name} provides relationship-focused tools, entertainment
              features, general relationship tips, and informational content.
              Our services are designed to provide a simple and enjoyable
              experience for users interested in relationships and love.
            </p>
          </section>

          <section>
            <h2 className="font-display text-lg font-bold text-gray-800 mb-2">
              3. Love Calculator
            </h2>

            <p>
              Loveons love compatibility results are provided for
              entertainment and general informational purposes only.
            </p>

            <p className="mt-3">
              Love percentages, compatibility scores, relationship stages,
              and suggestions generated by our tools are not scientific,
              psychological, medical, or professional assessments. They
              should not be treated as predictions or guarantees about a
              relationship.
            </p>

            <p className="mt-3">
              Results may be generated using simplified calculations or
              algorithms and may vary depending on the information entered.
            </p>
          </section>

          <section>
            <h2 className="font-display text-lg font-bold text-gray-800 mb-2">
              4. Relationship Tips & Information
            </h2>

            <p>
              Relationship tips and articles published on Loveons are
              intended for general informational purposes. They are not a
              substitute for professional relationship, psychological,
              medical, legal, or financial advice.
            </p>

            <p className="mt-3">
              You should use your own judgment when applying any information
              provided on the website.
            </p>
          </section>

          <section>
            <h2 className="font-display text-lg font-bold text-gray-800 mb-2">
              5. User-Provided Information
            </h2>

            <p>
              You are responsible for the information you enter into Loveons
              tools and forms. Please avoid submitting sensitive, confidential,
              or unnecessary personal information.
            </p>

            <p className="mt-3">
              You must not use the website to submit unlawful, abusive,
              threatening, defamatory, or harmful content.
            </p>
          </section>

          <section>
            <h2 className="font-display text-lg font-bold text-gray-800 mb-2">
              6. Acceptable Use
            </h2>

            <p>
              You agree to use Loveons only for lawful purposes. You must not
              attempt to interfere with the operation or security of the
              website, misuse its features, or attempt to gain unauthorized
              access to any part of the service.
            </p>
          </section>

          <section>
            <h2 className="font-display text-lg font-bold text-gray-800 mb-2">
              7. Intellectual Property
            </h2>

            <p>
              Unless otherwise stated, the Loveons name, logo, website design,
              original content, graphics, text, and other materials are owned
              by or licensed to Loveons and are protected by applicable
              intellectual property laws.
            </p>

            <p className="mt-3">
              You may not copy, reproduce, modify, distribute, or commercially
              exploit Loveons content without appropriate permission.
            </p>
          </section>

          <section>
            <h2 className="font-display text-lg font-bold text-gray-800 mb-2">
              8. Third-Party Services
            </h2>

            <p>
              Loveons may use third-party services to provide certain
              functionality, including email delivery, hosting, analytics,
              or other technical services. These services may have their own
              terms and privacy policies.
            </p>
          </section>

          <section>
            <h2 className="font-display text-lg font-bold text-gray-800 mb-2">
              9. Website Availability
            </h2>

            <p>
              We aim to keep Loveons available and reliable, but we do not
              guarantee that the website or any particular feature will always
              be available, uninterrupted, secure, or error-free.
            </p>
          </section>

          <section>
            <h2 className="font-display text-lg font-bold text-gray-800 mb-2">
              10. Disclaimer of Warranties
            </h2>

            <p>
              Loveons is provided on an "as is" and "as available" basis.
              We make no guarantees regarding the accuracy, completeness,
              reliability, or suitability of information, calculations,
              results, or recommendations provided through the website.
            </p>
          </section>

          <section>
            <h2 className="font-display text-lg font-bold text-gray-800 mb-2">
              11. Limitation of Liability
            </h2>

            <p>
              To the extent permitted by applicable law, Loveons and its
              operators will not be responsible for losses, damages, or
              consequences arising from your use of the website, reliance on
              calculator results, relationship tips, or other website content.
            </p>
          </section>

          <section>
            <h2 className="font-display text-lg font-bold text-gray-800 mb-2">
              12. Changes to These Terms
            </h2>

            <p>
              We may update these Terms & Conditions from time to time.
              Updated terms will be published on this page, and continued use
              of Loveons after changes are published means you accept the
              updated terms.
            </p>
          </section>

          <section>
            <h2 className="font-display text-lg font-bold text-gray-800 mb-2">
              13. Contact Us
            </h2>

            <p>
              If you have questions about these Terms & Conditions, you can
              contact the Loveons team at:
            </p>

            <a
              href={`mailto:${BRAND.email}`}
              className="inline-block mt-2 font-semibold text-rose-500 hover:text-rose-600"
            >
              {BRAND.email}
            </a>
          </section>

          <section className="pt-4 border-t border-gray-100">
            <p className="text-xs text-gray-400">
              Last updated: August 2026
            </p>
          </section>

        </div>
      </PageLayout>
    </>
  );
}

